import type { TechStackItem } from "@/types/tech-stack";

export const MOCK_TECH_STACKS: TechStackItem[] = [
  {
    id: "nextjs",
    name: "Next.js",
    slug: "nextjs",
    category: "Frontend",
    questionCount: 28,
    badgeText: "High Failure Rate",
    badgeTone: "warning",
    challengeQuestion: "How do Server Components handle caching in App Router?",
    iconName: "nextjs",
  },
  {
    id: "react",
    name: "React.js",
    slug: "react",
    category: "Frontend",
    questionCount: 42,
    badgeText: "Top Recruiter Choice",
    badgeTone: "accent",
    challengeQuestion: "When does useLayoutEffect run compared with useEffect?",
    iconName: "react",
  },
  {
    id: "typescript",
    name: "TypeScript",
    slug: "typescript",
    category: "Language",
    questionCount: 32,
    badgeText: "Must-Have 2026",
    badgeTone: "info",
    challengeQuestion: "Can you explain infer with conditional types?",
    iconName: "typescript",
  },
  {
    id: "javascript",
    name: "JavaScript",
    slug: "javascript",
    category: "Language",
    questionCount: 50,
    badgeText: "Core Technical Round",
    badgeTone: "warning",
    challengeQuestion: "How does the Event Loop process microtasks and macrotasks?",
    iconName: "javascript",
  },
  {
    id: "nodejs",
    name: "Node.js",
    slug: "nodejs",
    category: "Backend",
    questionCount: 24,
    badgeText: "Backend Benchmark",
    badgeTone: "success",
    challengeQuestion: "How can you prevent thread pool starvation at scale?",
    iconName: "nodejs",
  },
  {
    id: "express",
    name: "Express.js",
    slug: "express",
    category: "Backend",
    questionCount: 18,
    badgeText: "API Architecture",
    badgeTone: "accent",
    challengeQuestion: "How does async error propagation work in middleware?",
    iconName: "express",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    slug: "mongodb",
    category: "Database",
    questionCount: 22,
    badgeText: "Database Depth",
    badgeTone: "success",
    challengeQuestion: "When should aggregation replace simple indexes?",
    iconName: "mongodb",
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    slug: "tailwind",
    category: "Styling",
    questionCount: 15,
    badgeText: "UI Speed Round",
    badgeTone: "info",
    challengeQuestion: "How does Tailwind optimize generated utility classes?",
    iconName: "tailwind",
  },
  {
    id: "css3",
    name: "CSS3",
    slug: "css3",
    category: "Styling",
    questionCount: 20,
    badgeText: "Layout Mastery",
    badgeTone: "accent",
    challengeQuestion: "How does stacking context affect z-index rendering?",
    iconName: "css3",
  },
  {
    id: "html5",
    name: "HTML5",
    slug: "html5",
    category: "Frontend",
    questionCount: 12,
    badgeText: "Web Vitals & Accessibility",
    badgeTone: "info",
    challengeQuestion: "What is the difference between async and defer scripts?",
    iconName: "html5",
  },
];