import type { TechStackItem } from "@/types/tech-stack";

export const MOCK_TECH_STACKS: TechStackItem[] = [
  {
    id: "nextjs",
    name: "Next.js",
    slug: "nextjs",
    category: "Frontend",
    questionCount: 28,
    difficulty: "Hard",
    challengeQuestion: "How does App Router cache Server Components?",
    iconName: "nextjs",
  },
  {
    id: "react",
    name: "React.js",
    slug: "react",
    category: "Frontend",
    questionCount: 42,
    difficulty: "Medium",
    challengeQuestion: "When does useLayoutEffect run vs useEffect?",
    iconName: "react",
  },
  {
    id: "typescript",
    name: "TypeScript",
    slug: "typescript",
    category: "Language",
    questionCount: 32,
    difficulty: "Hard",
    challengeQuestion: "How does infer work in conditional types?",
    iconName: "typescript",
  },
  {
    id: "javascript",
    name: "JavaScript",
    slug: "javascript",
    category: "Language",
    questionCount: 50,
    difficulty: "Medium",
    challengeQuestion: "How does the event loop order microtasks?",
    iconName: "javascript",
  },
  {
    id: "nodejs",
    name: "Node.js",
    slug: "nodejs",
    category: "Backend",
    questionCount: 24,
    difficulty: "Hard",
    challengeQuestion: "How do you prevent thread pool starvation?",
    iconName: "nodejs",
  },
  {
    id: "express",
    name: "Express.js",
    slug: "express",
    category: "Backend",
    questionCount: 18,
    difficulty: "Hard",
    challengeQuestion: "How does async error handling work in middleware?",
    iconName: "express",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    slug: "mongodb",
    category: "Database",
    questionCount: 22,
    difficulty: "Medium",
    challengeQuestion: "When should aggregation replace simple indexes?",
    iconName: "mongodb",
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    slug: "tailwind",
    category: "Styling",
    questionCount: 15,
    difficulty: "Easy",
    challengeQuestion: "How does Tailwind purge unused utility classes?",
    iconName: "tailwind",
  },
  {
    id: "css3",
    name: "CSS3",
    slug: "css3",
    category: "Styling",
    questionCount: 20,
    difficulty: "Hard",
    challengeQuestion: "How does stacking context affect z-index?",
    iconName: "css3",
  },
  {
    id: "html5",
    name: "HTML5",
    slug: "html5",
    category: "Frontend",
    questionCount: 12,
    difficulty: "Easy",
    challengeQuestion: "What's the difference between async and defer?",
    iconName: "html5",
  },
];